<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Tests\Functional;

use PHPUnit\Framework\Attributes\DataProvider;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Uhifadhi\Entity\User;
use Uhifadhi\Enum\TeamRoleEnum;
use Uhifadhi\Factory\DepartmentFactory;
use Uhifadhi\Factory\PositionFactory;
use Uhifadhi\Factory\UserFactory;
use Uhifadhi\Repository\UserRepository;

/**
 * Creating a MEMBER from the team surface: the roster used to be read-only about people (a
 * position could be assigned, but the account itself only existed if a console command made it),
 * so the one act nobody could perform in the app was adding a colleague.
 *
 * The screen is Super Admin only — it hands out a tier, and a tier is the coarsest permission in
 * the app. There is NO email flow (deliberately: the deployment sends no mail); the password is
 * GENERATED by the app and shown to the creating admin exactly once, on the answer page, to be
 * handed over out of band.
 */
final class TeamMemberCreationTest extends AuthenticatedWebTestCase
{
    public function testTheTeamPageOffersNewMemberToASuperAdminOnly(): void
    {
        $client = static::createClient();

        $this->loginAs($client, TeamRoleEnum::SuperAdmin);
        $client->request('GET', '/team');
        self::assertSelectorExists('a[href="/team/members/new"]');

        $this->loginAs($client, TeamRoleEnum::Manager);
        $client->request('GET', '/team');
        self::assertSelectorNotExists('a[href="/team/members/new"]');
    }

    public function testTheScreenRendersForASuperAdmin(): void
    {
        $client = static::createClient();
        DepartmentFactory::createOne(['name' => 'Ecology']);
        PositionFactory::createOne(['name' => 'Ranger']);
        $this->loginAs($client, TeamRoleEnum::SuperAdmin);

        $client->request('GET', '/team/members/new');

        self::assertResponseIsSuccessful();
        self::assertSelectorExists('input[name="member[email]"]');
        self::assertSelectorExists('input[name="member[firstName]"]');
        self::assertSelectorExists('input[name="member[lastName]"]');
        self::assertSelectorExists('select[name="tier"]');
        self::assertSelectorExists('select[name="position"]');
        // No password field anywhere: the app generates it, the admin never invents one.
        self::assertSelectorNotExists('input[type="password"]');
    }

    /**
     * @return list<array{TeamRoleEnum}>
     */
    public static function lesserTiers(): array
    {
        return [[TeamRoleEnum::Admin], [TeamRoleEnum::Manager]];
    }

    #[DataProvider('lesserTiers')]
    public function testTiersBelowSuperAdminAreRefusedTheScreenAndTheWrite(TeamRoleEnum $tier): void
    {
        $client = static::createClient();
        $this->loginAs($client, $tier);

        $client->request('GET', '/team/members/new');
        self::assertResponseStatusCodeSame(403);

        $client->request('POST', '/team/members/new', [
            'member' => ['email' => 'sneak@authority.go.tz', 'firstName' => 'S', 'lastName' => 'Neak'],
            'tier' => TeamRoleEnum::SuperAdmin->value,
        ]);
        self::assertResponseStatusCodeSame(403);
        self::assertNull($this->users()->findOneByEmail('sneak@authority.go.tz'));
    }

    public function testASuperAdminCreatesAStaffMemberWhoCanThenSignIn(): void
    {
        $client = static::createClient();
        $ecology = DepartmentFactory::createOne(['name' => 'Ecology']);
        $ranger = PositionFactory::createOne(['name' => 'Ranger', 'department' => $ecology]);
        $this->loginAs($client, TeamRoleEnum::SuperAdmin);

        $crawler = $client->request('GET', '/team/members/new');
        $crawler = $client->submitForm('Create member', [
            'member[email]' => 'New.Ranger@authority.go.tz',
            'member[firstName]' => 'Neema',
            'member[lastName]' => 'Ranger',
            'member[_token]' => $crawler->filter('input[name="member[_token]"]')->attr('value'),
            'tier' => TeamRoleEnum::Staff->value,
            'position' => $ranger->getUuidString(),
        ]);

        self::assertResponseIsSuccessful();

        $created = $this->users()->findOneByEmail('new.ranger@authority.go.tz');
        self::assertInstanceOf(User::class, $created);
        self::assertSame('Neema', $created->getFirstName());
        self::assertSame(TeamRoleEnum::Staff, $created->getTeamRole());
        self::assertSame('Ranger', $created->getPosition()?->getName());
        self::assertTrue($created->isVerified(), 'there is no mail flow to verify through');

        // The password is on the answer page, once — and it is the real one.
        $password = trim($crawler->filter('[data-generated-password]')->text());
        self::assertMatchesRegularExpression('/^\S{16,}$/', $password);

        /** @var UserPasswordHasherInterface $hasher */
        $hasher = static::getContainer()->get(UserPasswordHasherInterface::class);
        self::assertTrue($hasher->isPasswordValid($created, $password));

        // Shown once: coming back to the blank screen does not show it again.
        $crawler = $client->request('GET', '/team/members/new');
        self::assertCount(0, $crawler->filter('[data-generated-password]'));
    }

    public function testAManagingTierIsCreatedWithoutAPositionEvenWhenOneIsPosted(): void
    {
        $client = static::createClient();
        $ranger = PositionFactory::createOne(['name' => 'Ranger']);
        $this->loginAs($client, TeamRoleEnum::SuperAdmin);

        $crawler = $client->request('GET', '/team/members/new');
        $client->submitForm('Create member', [
            'member[email]' => 'admin2@authority.go.tz',
            'member[firstName]' => 'Asha',
            'member[lastName]' => 'Mkuu',
            'member[_token]' => $crawler->filter('input[name="member[_token]"]')->attr('value'),
            'tier' => TeamRoleEnum::Admin->value,
            'position' => $ranger->getUuidString(),
        ]);

        self::assertResponseIsSuccessful();
        $created = $this->users()->findOneByEmail('admin2@authority.go.tz');
        self::assertSame(TeamRoleEnum::Admin, $created?->getTeamRole());
        self::assertNull($created->getPosition(), 'managing tiers hold everything by tier');
    }

    public function testAnEmailAlreadyOnTheRosterIsRefusedInWords(): void
    {
        $client = static::createClient();
        UserFactory::createOne(['email' => 'taken@authority.go.tz']);
        $this->loginAs($client, TeamRoleEnum::SuperAdmin);

        $crawler = $client->request('GET', '/team/members/new');
        $crawler = $client->submitForm('Create member', [
            'member[email]' => 'taken@authority.go.tz',
            'member[firstName]' => 'Twin',
            'member[lastName]' => 'Account',
            'member[_token]' => $crawler->filter('input[name="member[_token]"]')->attr('value'),
            'tier' => TeamRoleEnum::Staff->value,
        ]);

        self::assertResponseIsSuccessful();
        self::assertStringContainsString('already', $crawler->filter('.tm-flash')->text());
        self::assertCount(1, $this->users()->findBy(['email' => 'taken@authority.go.tz']));
        self::assertCount(0, $crawler->filter('[data-generated-password]'));
    }

    private function users(): UserRepository
    {
        /** @var UserRepository $repository */
        $repository = static::getContainer()->get(UserRepository::class);

        return $repository;
    }
}
