<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260824175715 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Custom widget presets — user-named layouts per surface (paired partial unique indexes, org-wide vs area rows).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE widget_custom_preset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, surface VARCHAR(64) NOT NULL, user_id INT NOT NULL, area_uuid UUID DEFAULT NULL, name VARCHAR(60) NOT NULL, layout JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_82A9B355D17F50A6 ON widget_custom_preset (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_widget_preset_surface_user_area_name ON widget_custom_preset (surface, user_id, area_uuid, name) WHERE (area_uuid IS NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_widget_preset_surface_user_org_name ON widget_custom_preset (surface, user_id, name) WHERE (area_uuid IS NULL)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE widget_custom_preset');
    }
}
