<?php

/*
 * Copyright (C) 2026 Uhifadhi Labs
 *
 * This file is part of uhifadhi and is proprietary software.
 * Unauthorized copying, modification or distribution is prohibited.
 */

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Patrol batch: amendments, photo geolocation, widget-framework migration.
 *
 * - patrol_observation_amendment: the append-only correction trail on a synced
 *   observation — rows are only ever added, never edited or removed.
 * - patrol_observation_photo gains where the shutter fired (position/accuracy_m,
 *   PostGIS point + gist index) and the from_amendment flag.
 * - patrol_widget_preference is dropped: the patrols surface now stores layouts
 *   in the host's widget_preference like every other module. Stored layouts do
 *   not migrate — nothing was released, re-choosing a design is the upgrade path.
 */
final class Version20260828060000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Patrol: observation amendments, photo geolocation, host widget framework';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patrol_observation_amendment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, kind VARCHAR(40) NOT NULL, body TEXT NOT NULL, superseded_value TEXT DEFAULT NULL, written_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_name VARCHAR(120) DEFAULT NULL, observation_id INT NOT NULL, author_id INT DEFAULT NULL, photo_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_282D403FD17F50A6 ON patrol_observation_amendment (uuid)');
        $this->addSql('CREATE INDEX IDX_282D403F1409DD88 ON patrol_observation_amendment (observation_id)');
        $this->addSql('CREATE INDEX IDX_282D403FF675F31B ON patrol_observation_amendment (author_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_282D403F7E9E4C8C ON patrol_observation_amendment (photo_id)');
        $this->addSql('CREATE INDEX idx_patrol_amendment_observation ON patrol_observation_amendment (observation_id, written_at)');
        $this->addSql('ALTER TABLE patrol_observation_amendment ADD CONSTRAINT FK_282D403F1409DD88 FOREIGN KEY (observation_id) REFERENCES patrol_observation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_amendment ADD CONSTRAINT FK_282D403FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_amendment ADD CONSTRAINT FK_282D403F7E9E4C8C FOREIGN KEY (photo_id) REFERENCES patrol_observation_photo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('DROP TABLE patrol_widget_preference');
        $this->addSql('ALTER TABLE patrol_observation_photo ADD position geometry(POINT,4326) DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation_photo ADD accuracy_m DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation_photo ADD from_amendment BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('CREATE INDEX idx_patrol_observation_photo_position_sp ON patrol_observation_photo USING gist (position)');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('the amendment trail is append-only evidence; there is no path back');
    }
}
