<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260815202928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE forest_loss_year DROP CONSTRAINT fk_1e1f1912b626396b');
        $this->addSql('DROP TABLE forest_loss_year');
        $this->addSql('DROP TABLE hansen_loss_polygon');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE forest_loss_year (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year SMALLINT NOT NULL, geom geometry(MULTIPOLYGON,4326) NOT NULL, area_ha DOUBLE PRECISION NOT NULL, source VARCHAR(64) NOT NULL, aoi_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_1e1f1912b626396b ON forest_loss_year (aoi_id)');
        $this->addSql('CREATE INDEX idx_forest_loss_year_geom_sp ON forest_loss_year (geom)');
        $this->addSql('CREATE TABLE hansen_loss_polygon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dn SMALLINT NOT NULL, geom geometry(POLYGON,4326) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_hansen_loss_polygon_geom_sp ON hansen_loss_polygon (geom)');
        $this->addSql('ALTER TABLE forest_loss_year ADD CONSTRAINT fk_1e1f1912b626396b FOREIGN KEY (aoi_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
