<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260808211553 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE hansen_loss_polygon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dn SMALLINT NOT NULL, geom geometry(POLYGON,4326) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_hansen_loss_polygon_geom_sp ON hansen_loss_polygon USING gist (geom)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE hansen_loss_polygon');
    }
}
