<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260825075313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, device_id VARCHAR(64) DEFAULT NULL, device_name VARCHAR(120) DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EBB3BC57DA ON api_token (token_hash)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EBD17F50A6 ON api_token (uuid)');
        $this->addSql('CREATE INDEX IDX_7BA2F5EB7E3C61F9 ON api_token (owner_id)');
        $this->addSql('CREATE TABLE patrol_flight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, sequence INT DEFAULT 1 NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, launch_point_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18A64BC7E393C4 ON patrol_flight (client_uuid)');
        $this->addSql('CREATE INDEX IDX_18A64BC7A7B49BA9 ON patrol_flight (patrol_id)');
        $this->addSql('CREATE INDEX IDX_18A64BC7A495DAEF ON patrol_flight (launch_point_id)');
        $this->addSql('CREATE TABLE patrol_launch_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, label VARCHAR(40) NOT NULL, name VARCHAR(120) DEFAULT NULL, position geometry(POINT,4326) NOT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, satellites INT DEFAULT NULL, established_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sector_type VARCHAR(255) NOT NULL, sector_radius_m DOUBLE PRECISION DEFAULT NULL, sector_polygon geometry(POLYGON,4326) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29E0744AE393C4 ON patrol_launch_point (client_uuid)');
        $this->addSql('CREATE INDEX IDX_29E0744AA7B49BA9 ON patrol_launch_point (patrol_id)');
        $this->addSql('CREATE INDEX idx_patrol_launch_point_position_sp ON patrol_launch_point USING gist (position)');
        $this->addSql('CREATE INDEX idx_patrol_launch_point_sector_polygon_sp ON patrol_launch_point USING gist (sector_polygon)');
        $this->addSql('CREATE TABLE patrol_observation_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, storage_path VARCHAR(255) NOT NULL, mime_type VARCHAR(100) DEFAULT NULL, byte_size INT DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3FCCB83CE393C4 ON patrol_observation_photo (client_uuid)');
        $this->addSql('CREATE INDEX IDX_3FCCB83C1409DD88 ON patrol_observation_photo (observation_id)');
        $this->addSql('CREATE TABLE patrol_track_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, batch_key VARCHAR(120) NOT NULL, point_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C298F73A7B49BA9 ON patrol_track_batch (patrol_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patrol_track_batch_key ON patrol_track_batch (batch_key)');
        $this->addSql('CREATE TABLE patrol_track_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position geometry(POINT,4326) NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, satellites INT DEFAULT NULL, elevation_m DOUBLE PRECISION DEFAULT NULL, speed_ms DOUBLE PRECISION DEFAULT NULL, patrol_id INT NOT NULL, batch_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_53872E83A7B49BA9 ON patrol_track_point (patrol_id)');
        $this->addSql('CREATE INDEX IDX_53872E83F39EBE7A ON patrol_track_point (batch_id)');
        $this->addSql('CREATE INDEX idx_patrol_track_point_patrol_time ON patrol_track_point (patrol_id, recorded_at)');
        $this->addSql('CREATE INDEX idx_patrol_track_point_position_sp ON patrol_track_point USING gist (position)');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_flight ADD CONSTRAINT FK_18A64BC7A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_flight ADD CONSTRAINT FK_18A64BC7A495DAEF FOREIGN KEY (launch_point_id) REFERENCES patrol_launch_point (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_launch_point ADD CONSTRAINT FK_29E0744AA7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_photo ADD CONSTRAINT FK_3FCCB83C1409DD88 FOREIGN KEY (observation_id) REFERENCES patrol_observation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_track_batch ADD CONSTRAINT FK_1C298F73A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_track_point ADD CONSTRAINT FK_53872E83A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_track_point ADD CONSTRAINT FK_53872E83F39EBE7A FOREIGN KEY (batch_id) REFERENCES patrol_track_batch (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD client_uuid UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD position_source VARCHAR(255) DEFAULT \'gps\' NOT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD accuracy_m DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD satellites INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD photo_count INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD launch_point_client_uuid UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD flight_client_uuid UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD launch_point_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD flight_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0A495DAEF FOREIGN KEY (launch_point_id) REFERENCES patrol_launch_point (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E091F478C5 FOREIGN KEY (flight_id) REFERENCES patrol_flight (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51A3A4E0E393C4 ON patrol_observation (client_uuid)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0A495DAEF ON patrol_observation (launch_point_id)');
        $this->addSql('CREATE INDEX IDX_51A3A4E091F478C5 ON patrol_observation (flight_id)');
        $this->addSql('ALTER TABLE patrol_patrol ADD client_uuid UUID DEFAULT NULL');
        // Existing rows (seeded demo patrols) predate the column — backfill an
        // empty roster, then drop the default so new writes must be explicit.
        $this->addSql('ALTER TABLE patrol_patrol ADD team_ranger_ids JSON DEFAULT \'[]\' NOT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ALTER team_ranger_ids DROP DEFAULT');
        $this->addSql('ALTER TABLE patrol_patrol ADD status VARCHAR(255) DEFAULT \'complete\' NOT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD drone_id VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD mission VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD device_id VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD app_version VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD web_edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10A8EB8E393C4 ON patrol_patrol (client_uuid)');
        $this->addSql('ALTER TABLE "user" ADD ranger_code VARCHAR(32) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649CE15BE12 ON "user" (ranger_code)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_token DROP CONSTRAINT FK_7BA2F5EB7E3C61F9');
        $this->addSql('ALTER TABLE patrol_flight DROP CONSTRAINT FK_18A64BC7A7B49BA9');
        $this->addSql('ALTER TABLE patrol_flight DROP CONSTRAINT FK_18A64BC7A495DAEF');
        $this->addSql('ALTER TABLE patrol_launch_point DROP CONSTRAINT FK_29E0744AA7B49BA9');
        $this->addSql('ALTER TABLE patrol_observation_photo DROP CONSTRAINT FK_3FCCB83C1409DD88');
        $this->addSql('ALTER TABLE patrol_track_batch DROP CONSTRAINT FK_1C298F73A7B49BA9');
        $this->addSql('ALTER TABLE patrol_track_point DROP CONSTRAINT FK_53872E83A7B49BA9');
        $this->addSql('ALTER TABLE patrol_track_point DROP CONSTRAINT FK_53872E83F39EBE7A');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP TABLE patrol_flight');
        $this->addSql('DROP TABLE patrol_launch_point');
        $this->addSql('DROP TABLE patrol_observation_photo');
        $this->addSql('DROP TABLE patrol_track_batch');
        $this->addSql('DROP TABLE patrol_track_point');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0A495DAEF');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E091F478C5');
        $this->addSql('DROP INDEX UNIQ_51A3A4E0E393C4');
        $this->addSql('DROP INDEX IDX_51A3A4E0A495DAEF');
        $this->addSql('DROP INDEX IDX_51A3A4E091F478C5');
        $this->addSql('ALTER TABLE patrol_observation DROP client_uuid');
        $this->addSql('ALTER TABLE patrol_observation DROP position_source');
        $this->addSql('ALTER TABLE patrol_observation DROP accuracy_m');
        $this->addSql('ALTER TABLE patrol_observation DROP satellites');
        $this->addSql('ALTER TABLE patrol_observation DROP photo_count');
        $this->addSql('ALTER TABLE patrol_observation DROP launch_point_client_uuid');
        $this->addSql('ALTER TABLE patrol_observation DROP flight_client_uuid');
        $this->addSql('ALTER TABLE patrol_observation DROP launch_point_id');
        $this->addSql('ALTER TABLE patrol_observation DROP flight_id');
        $this->addSql('DROP INDEX UNIQ_D10A8EB8E393C4');
        $this->addSql('ALTER TABLE patrol_patrol DROP client_uuid');
        $this->addSql('ALTER TABLE patrol_patrol DROP team_ranger_ids');
        $this->addSql('ALTER TABLE patrol_patrol DROP status');
        $this->addSql('ALTER TABLE patrol_patrol DROP drone_id');
        $this->addSql('ALTER TABLE patrol_patrol DROP mission');
        $this->addSql('ALTER TABLE patrol_patrol DROP device_id');
        $this->addSql('ALTER TABLE patrol_patrol DROP app_version');
        $this->addSql('ALTER TABLE patrol_patrol DROP web_edited_at');
        $this->addSql('DROP INDEX UNIQ_8D93D649CE15BE12');
        $this->addSql('ALTER TABLE "user" DROP ranger_code');
    }
}
