<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260824190638 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Zones — the spatial lens: named non-overlapping MultiPolygons subdividing an area (unique name per area, GiST index, cascade with the area).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, geom geometry(MULTIPOLYGON,4326) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A0EBC007D17F50A6 ON zone (uuid)');
        $this->addSql('CREATE INDEX IDX_A0EBC007BD0F409C ON zone (area_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_zone_area_name ON zone (area_id, name)');
        $this->addSql('CREATE INDEX idx_zone_geom_sp ON zone USING gist (geom)');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC007BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC007BD0F409C');
        $this->addSql('DROP TABLE zone');
    }
}
