<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260824145246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Departments (org lens: department + module attachments + position.department) and the host widget-preference store (partial unique indexes for org-wide vs area rows).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD1DE18A5E237E06 ON department (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD1DE18AD17F50A6 ON department (uuid)');
        $this->addSql('CREATE TABLE department_module (department_id INT NOT NULL, module_id INT NOT NULL, PRIMARY KEY (department_id, module_id))');
        $this->addSql('CREATE INDEX IDX_183ED9D8AE80F5DF ON department_module (department_id)');
        $this->addSql('CREATE INDEX IDX_183ED9D8AFC2B591 ON department_module (module_id)');
        $this->addSql('CREATE TABLE widget_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, surface VARCHAR(64) NOT NULL, user_id INT NOT NULL, area_uuid UUID DEFAULT NULL, prefs JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_widget_pref_surface_user_area ON widget_preference (surface, user_id, area_uuid) WHERE (area_uuid IS NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_widget_pref_surface_user_org ON widget_preference (surface, user_id) WHERE (area_uuid IS NULL)');
        $this->addSql('ALTER TABLE department_module ADD CONSTRAINT FK_183ED9D8AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE department_module ADD CONSTRAINT FK_183ED9D8AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "position" ADD department_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "position" ADD CONSTRAINT FK_462CE4F5AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_462CE4F5AE80F5DF ON "position" (department_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE department_module DROP CONSTRAINT FK_183ED9D8AE80F5DF');
        $this->addSql('ALTER TABLE department_module DROP CONSTRAINT FK_183ED9D8AFC2B591');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE department_module');
        $this->addSql('DROP TABLE widget_preference');
        $this->addSql('ALTER TABLE position DROP CONSTRAINT FK_462CE4F5AE80F5DF');
        $this->addSql('DROP INDEX IDX_462CE4F5AE80F5DF');
        $this->addSql('ALTER TABLE position DROP department_id');
    }
}
