<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260823145345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema — the lean flat host (areas, team, module seam) plus the installed module bundles (patrol).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS postgis');
        $this->addSql('CREATE TABLE area_module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, aoi_id INT NOT NULL, module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6AAFD7AAD17F50A6 ON area_module (uuid)');
        $this->addSql('CREATE INDEX IDX_6AAFD7AAB626396B ON area_module (aoi_id)');
        $this->addSql('CREATE INDEX IDX_6AAFD7AAAFC2B591 ON area_module (module_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_area_module ON area_module (aoi_id, module_id)');
        $this->addSql('CREATE TABLE area_of_interest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, geom geometry(MULTIPOLYGON,4326) NOT NULL, source VARCHAR(64) NOT NULL, iucn_category VARCHAR(8) DEFAULT NULL, established_year INT DEFAULT NULL, tree_cover_pct DOUBLE PRECISION DEFAULT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB9E46FCD17F50A6 ON area_of_interest (uuid)');
        $this->addSql('CREATE INDEX idx_area_of_interest_geom_sp ON area_of_interest USING gist (geom)');
        $this->addSql('CREATE TABLE module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(40) NOT NULL, name VARCHAR(80) NOT NULL, category VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, data_source VARCHAR(80) NOT NULL, pinned BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C242628989D9B62 ON module (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C242628D17F50A6 ON module (uuid)');
        $this->addSql('CREATE TABLE patrol_observation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, category VARCHAR(40) NOT NULL, note TEXT DEFAULT NULL, position geometry(POINT,4326) DEFAULT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, recorded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51A3A4E0D17F50A6 ON patrol_observation (uuid)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0A7B49BA9 ON patrol_observation (patrol_id)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0D05A957B ON patrol_observation (recorded_by_id)');
        $this->addSql('CREATE INDEX idx_patrol_observation_position_sp ON patrol_observation USING gist (position)');
        $this->addSql('CREATE TABLE patrol_patrol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, type VARCHAR(40) NOT NULL, station VARCHAR(80) DEFAULT NULL, team VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, distance_km DOUBLE PRECISION DEFAULT NULL, source VARCHAR(255) NOT NULL, track geometry(LINESTRING,4326) DEFAULT NULL, point_count INT DEFAULT NULL, gap_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, lead_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10A8EB8D17F50A6 ON patrol_patrol (uuid)');
        $this->addSql('CREATE INDEX IDX_D10A8EB8BD0F409C ON patrol_patrol (area_id)');
        $this->addSql('CREATE INDEX IDX_D10A8EB855458D ON patrol_patrol (lead_id)');
        $this->addSql('CREATE INDEX idx_patrol_patrol_track_sp ON patrol_patrol USING gist (track)');
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, permissions JSON NOT NULL, locked BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_462CE4F5D17F50A6 ON position (uuid)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, roles JSON NOT NULL, team_role VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, verification_token VARCHAR(100) DEFAULT NULL, password_reset_token VARCHAR(100) DEFAULT NULL, password_reset_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, position_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649D17F50A6 ON "user" (uuid)');
        $this->addSql('CREATE INDEX IDX_8D93D649DD842E46 ON "user" (position_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE area_module ADD CONSTRAINT FK_6AAFD7AAB626396B FOREIGN KEY (aoi_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE area_module ADD CONSTRAINT FK_6AAFD7AAAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0D05A957B FOREIGN KEY (recorded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB8BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB855458D FOREIGN KEY (lead_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE area_module DROP CONSTRAINT FK_6AAFD7AAB626396B');
        $this->addSql('ALTER TABLE area_module DROP CONSTRAINT FK_6AAFD7AAAFC2B591');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0A7B49BA9');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0D05A957B');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB8BD0F409C');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB855458D');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649DD842E46');
        $this->addSql('DROP TABLE area_module');
        $this->addSql('DROP TABLE area_of_interest');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP TABLE patrol_observation');
        $this->addSql('DROP TABLE patrol_patrol');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
