<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Provenance for ingestion: one dataset_run row per pipeline execution.
 * (Hand-trimmed: the generator also tried to drop OGR's ogr_system_tables
 * bookkeeping — now excluded for good via doctrine.dbal.schema_filter.)
 */
final class Version20260808185943 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add dataset_run (ingestion provenance)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE dataset_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dataset VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, params JSON NOT NULL, report JSON DEFAULT NULL, error TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE dataset_run');
    }
}
