<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260823081152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patrol_observation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, category VARCHAR(40) NOT NULL, note TEXT DEFAULT NULL, position geometry(POINT,4326) DEFAULT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, recorded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51A3A4E0D17F50A6 ON patrol_observation (uuid)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0A7B49BA9 ON patrol_observation (patrol_id)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0D05A957B ON patrol_observation (recorded_by_id)');
        $this->addSql('CREATE INDEX idx_patrol_observation_position_sp ON patrol_observation USING gist (position)');
        $this->addSql('CREATE TABLE patrol_patrol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, type VARCHAR(40) NOT NULL, station VARCHAR(80) DEFAULT NULL, team VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, distance_km DOUBLE PRECISION DEFAULT NULL, source VARCHAR(255) NOT NULL, track geometry(LINESTRING,4326) DEFAULT NULL, point_count INT DEFAULT NULL, gap_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, lead_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10A8EB8D17F50A6 ON patrol_patrol (uuid)');
        $this->addSql('CREATE INDEX IDX_D10A8EB8BD0F409C ON patrol_patrol (area_id)');
        $this->addSql('CREATE INDEX IDX_D10A8EB855458D ON patrol_patrol (lead_id)');
        $this->addSql('CREATE INDEX idx_patrol_patrol_track_sp ON patrol_patrol USING gist (track)');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0D05A957B FOREIGN KEY (recorded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB8BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB855458D FOREIGN KEY (lead_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0A7B49BA9');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0D05A957B');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB8BD0F409C');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB855458D');
        $this->addSql('DROP TABLE patrol_observation');
        $this->addSql('DROP TABLE patrol_patrol');
    }
}
