<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812212334 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Composition: visualization table (per-module configured charts)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE visualization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(80) NOT NULL, type VARCHAR(255) NOT NULL, x_axis VARCHAR(40) NOT NULL, y_axis VARCHAR(40) NOT NULL, colour_by VARCHAR(40) DEFAULT NULL, aggregation VARCHAR(20) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, area_module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E0936C40D17F50A6 ON visualization (uuid)');
        $this->addSql('CREATE INDEX IDX_E0936C403ABEF04D ON visualization (area_module_id)');
        $this->addSql('ALTER TABLE visualization ADD CONSTRAINT FK_E0936C403ABEF04D FOREIGN KEY (area_module_id) REFERENCES area_module (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE visualization DROP CONSTRAINT FK_E0936C403ABEF04D');
        $this->addSql('DROP TABLE visualization');
    }
}
