<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260818062921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE uhakiki_campaign (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(120) NOT NULL, subject VARCHAR(60) NOT NULL, label_taxonomy JSON NOT NULL, plate_radius_m DOUBLE PRECISION NOT NULL, required_verdicts INT NOT NULL, relocation_tolerance_m DOUBLE PRECISION NOT NULL, snap_radius_m DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB8CD0D17F50A6 ON uhakiki_campaign (uuid)');
        $this->addSql('CREATE TABLE uhakiki_candidate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, point geometry(POINT,4326) NOT NULL, resolved_point geometry(POINT,4326) DEFAULT NULL, status VARCHAR(20) NOT NULL, origin VARCHAR(20) NOT NULL, source_ref VARCHAR(180) DEFAULT NULL, campaign_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B61C1C67D17F50A6 ON uhakiki_candidate (uuid)');
        $this->addSql('CREATE INDEX IDX_B61C1C67F639F774 ON uhakiki_candidate (campaign_id)');
        $this->addSql('CREATE INDEX idx_uhakiki_candidate_point_sp ON uhakiki_candidate USING gist (point)');
        $this->addSql('CREATE INDEX idx_uhakiki_candidate_resolved_point_sp ON uhakiki_candidate USING gist (resolved_point)');
        $this->addSql('CREATE TABLE uhakiki_verdict (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, reviewer_id VARCHAR(64) NOT NULL, verdict VARCHAR(10) NOT NULL, label VARCHAR(80) DEFAULT NULL, note TEXT DEFAULT NULL, moved_point geometry(POINT,4326) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17186940D17F50A6 ON uhakiki_verdict (uuid)');
        $this->addSql('CREATE INDEX IDX_1718694091BD8781 ON uhakiki_verdict (candidate_id)');
        $this->addSql('CREATE INDEX idx_uhakiki_verdict_moved_point_sp ON uhakiki_verdict USING gist (moved_point)');
        $this->addSql('ALTER TABLE uhakiki_candidate ADD CONSTRAINT FK_B61C1C67F639F774 FOREIGN KEY (campaign_id) REFERENCES uhakiki_campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE uhakiki_verdict ADD CONSTRAINT FK_1718694091BD8781 FOREIGN KEY (candidate_id) REFERENCES uhakiki_candidate (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE uhakiki_candidate DROP CONSTRAINT FK_B61C1C67F639F774');
        $this->addSql('ALTER TABLE uhakiki_verdict DROP CONSTRAINT FK_1718694091BD8781');
        $this->addSql('DROP TABLE uhakiki_campaign');
        $this->addSql('DROP TABLE uhakiki_candidate');
        $this->addSql('DROP TABLE uhakiki_verdict');
    }
}
