<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The five-port integration batch: department goals, the position naming
 * uniques, and the active-preset columns.
 *
 * - department_goal: a department's declared targets (statement, target,
 *   kpi ref, period), owned by an optional position. Goals die with their
 *   department (CASCADE) but survive an owner position's deletion (SET NULL)
 *   — a target outlives the seat that set it.
 * - position: paired partial uniques — names are unique within a department,
 *   and unique among the unfiled; the same name may exist in two departments
 *   ("Ecology / Analyst" and "Protection Service / Analyst").
 * - widget_preference.active_kind/active_preset: the active-preset model —
 *   a dashboard always reflects a named preset, never an anonymous layout.
 */
final class Version20260825190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'department_goal table, position partial unique names, widget_preference active-preset columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE department_goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statement VARCHAR(240) NOT NULL, target_value DOUBLE PRECISION NOT NULL, target_unit VARCHAR(24) NOT NULL, kpi_ref VARCHAR(60) NOT NULL, period VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, department_id INT NOT NULL, owning_position_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5EC68C7BD17F50A6 ON department_goal (uuid)');
        $this->addSql('CREATE INDEX IDX_5EC68C7BAE80F5DF ON department_goal (department_id)');
        $this->addSql('CREATE INDEX IDX_5EC68C7BD32C6495 ON department_goal (owning_position_id)');
        $this->addSql('ALTER TABLE department_goal ADD CONSTRAINT FK_5EC68C7BAE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE department_goal ADD CONSTRAINT FK_5EC68C7BD32C6495 FOREIGN KEY (owning_position_id) REFERENCES position (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_department_name ON "position" (department_id, name) WHERE (department_id IS NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_unfiled_name ON "position" (name) WHERE (department_id IS NULL)');
        $this->addSql('ALTER TABLE widget_preference ADD active_kind VARCHAR(8) DEFAULT NULL');
        $this->addSql('ALTER TABLE widget_preference ADD active_preset VARCHAR(64) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE widget_preference DROP active_preset');
        $this->addSql('ALTER TABLE widget_preference DROP active_kind');
        $this->addSql('DROP INDEX uniq_position_unfiled_name');
        $this->addSql('DROP INDEX uniq_position_department_name');
        $this->addSql('DROP TABLE department_goal');
    }
}
