<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814202235 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE module_feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_slug VARCHAR(64) NOT NULL, dataset_key VARCHAR(64) NOT NULL, label VARCHAR(64) NOT NULL, geom geometry(MULTIPOLYGON,4326) NOT NULL, aoi_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B4AC4B7FB626396B ON module_feature (aoi_id)');
        $this->addSql('CREATE INDEX idx_module_feature_lookup ON module_feature (aoi_id, module_slug, dataset_key)');
        $this->addSql('CREATE INDEX idx_module_feature_geom_sp ON module_feature USING gist (geom)');
        $this->addSql('CREATE TABLE module_feature_staging (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(64) NOT NULL, geom geometry(POLYGON,4326) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_module_feature_staging_geom_sp ON module_feature_staging USING gist (geom)');
        $this->addSql('ALTER TABLE module_feature ADD CONSTRAINT FK_B4AC4B7FB626396B FOREIGN KEY (aoi_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE module_feature DROP CONSTRAINT FK_B4AC4B7FB626396B');
        $this->addSql('DROP TABLE module_feature');
        $this->addSql('DROP TABLE module_feature_staging');
    }
}
