<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821120313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'uhakiki: audit log (every workflow transition, actor + reason) and the feature\'s imported-at moment.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE uhakiki_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, from_status VARCHAR(20) DEFAULT NULL, to_status VARCHAR(20) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, feature_id INT NOT NULL, performed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_884F52D62E65C292 ON uhakiki_audit_log (performed_by_id)');
        $this->addSql('CREATE INDEX idx_uhakiki_audit_log_feature ON uhakiki_audit_log (feature_id)');
        $this->addSql('ALTER TABLE uhakiki_audit_log ADD CONSTRAINT FK_884F52D660E4B879 FOREIGN KEY (feature_id) REFERENCES uhakiki_feature (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE uhakiki_audit_log ADD CONSTRAINT FK_884F52D62E65C292 FOREIGN KEY (performed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        // NOT NULL on a populated table needs a backfill: existing features get
        // the migration moment as their imported-at, then the default is dropped
        // so every future insert must state its own (the entity always does).
        $this->addSql('ALTER TABLE uhakiki_feature ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE uhakiki_feature ALTER COLUMN created_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE uhakiki_audit_log DROP CONSTRAINT FK_884F52D660E4B879');
        $this->addSql('ALTER TABLE uhakiki_audit_log DROP CONSTRAINT FK_884F52D62E65C292');
        $this->addSql('DROP TABLE uhakiki_audit_log');
        $this->addSql('ALTER TABLE uhakiki_feature DROP created_at');
    }
}
