<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814105853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Generic per-module dataset store (module_dataset), keyed by (area, module slug, dataset key).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE module_dataset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_slug VARCHAR(64) NOT NULL, dataset_key VARCHAR(64) NOT NULL, kind VARCHAR(16) NOT NULL, columns JSON DEFAULT NULL, rows JSON DEFAULT NULL, path VARCHAR(512) DEFAULT NULL, source VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, run_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CDB7FC9BD0F409C ON module_dataset (area_id)');
        $this->addSql('CREATE INDEX IDX_1CDB7FC984E3FEC4 ON module_dataset (run_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_dataset_area_module_key ON module_dataset (area_id, module_slug, dataset_key)');
        $this->addSql('ALTER TABLE module_dataset ADD CONSTRAINT FK_1CDB7FC9BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_dataset ADD CONSTRAINT FK_1CDB7FC984E3FEC4 FOREIGN KEY (run_id) REFERENCES dataset_run (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE module_dataset DROP CONSTRAINT FK_1CDB7FC9BD0F409C');
        $this->addSql('ALTER TABLE module_dataset DROP CONSTRAINT FK_1CDB7FC984E3FEC4');
        $this->addSql('DROP TABLE module_dataset');
    }
}
