<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812202716 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Composition context: module catalogue + per-area module activation (module, area_module)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE area_module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, active BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, aoi_id INT NOT NULL, module_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6AAFD7AAD17F50A6 ON area_module (uuid)');
        $this->addSql('CREATE INDEX IDX_6AAFD7AAB626396B ON area_module (aoi_id)');
        $this->addSql('CREATE INDEX IDX_6AAFD7AAAFC2B591 ON area_module (module_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_area_module ON area_module (aoi_id, module_id)');
        $this->addSql('CREATE TABLE module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(40) NOT NULL, name VARCHAR(80) NOT NULL, category VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, data_source VARCHAR(80) NOT NULL, pinned BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C242628989D9B62 ON module (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C242628D17F50A6 ON module (uuid)');
        $this->addSql('ALTER TABLE area_module ADD CONSTRAINT FK_6AAFD7AAB626396B FOREIGN KEY (aoi_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE area_module ADD CONSTRAINT FK_6AAFD7AAAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE area_module DROP CONSTRAINT FK_6AAFD7AAB626396B');
        $this->addSql('ALTER TABLE area_module DROP CONSTRAINT FK_6AAFD7AAAFC2B591');
        $this->addSql('DROP TABLE area_module');
        $this->addSql('DROP TABLE module');
    }
}
