<?php

declare(strict_types=1);

/*
 * This file is part of uhifadhi.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Discarded patrols and the append-only patrol history.
 *
 * - patrol_event: what happened to a patrol (renamed, type_changed,
 *   discarded), idempotent by clientUuid, dying with its patrol, keeping
 *   its story when the actor account goes.
 * - patrol_patrol: a name (patrols are renameable from the field), the
 *   discard reason, and the review hold that stops the retention clock.
 */
final class Version20260827140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'patrol_event table; patrol name, discardReason and review hold';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patrol_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, kind VARCHAR(40) NOT NULL, at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payload JSON NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patrol_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AABB13CCE393C4 ON patrol_event (client_uuid)');
        $this->addSql('CREATE INDEX IDX_AABB13CCA7B49BA9 ON patrol_event (patrol_id)');
        $this->addSql('CREATE INDEX IDX_AABB13CC10DAF24A ON patrol_event (actor_id)');
        $this->addSql('ALTER TABLE patrol_event ADD CONSTRAINT FK_AABB13CCA7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_event ADD CONSTRAINT FK_AABB13CC10DAF24A FOREIGN KEY (actor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD name VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD discard_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD held_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD held_by_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_D10A8EB85EEE5820 ON patrol_patrol (held_by_id)');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB85EEE5820 FOREIGN KEY (held_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB85EEE5820');
        $this->addSql('DROP INDEX IDX_D10A8EB85EEE5820');
        $this->addSql('ALTER TABLE patrol_patrol DROP held_by_id');
        $this->addSql('ALTER TABLE patrol_patrol DROP held_at');
        $this->addSql('ALTER TABLE patrol_patrol DROP discard_reason');
        $this->addSql('ALTER TABLE patrol_patrol DROP name');
        $this->addSql('DROP TABLE patrol_event');
    }
}
